### ISSUE TITLE
Problema com alguns valores nas notas.

### ISSUE THREAD

**Issue by andrelucassvt** [andrelucassvt/Calcular_notas_UNAMA#1]
O programa não está mostrando o resultado nas notas com o valor "3" e "5". 

Se colocar "3" na nota da primeira avaliação e "5" na nota da prova colegiada e virse versa, o programa não esta gerando resultado algum. 
Outros valores funcionam normalmente.

**Comment by Diogo-Felipe** [comment]
Vou pegar o problema para resolver, acabei de forkar ele.

**Comment by Diogo-Felipe** [comment]
A variável "calculo", quando as notas somam 8, é igual a 4.
No código eram testados o caso em que essa variável era testada nos casos em que ela era maior ou menor que 4, mas nunca no caso em que a variável era igual.
Eu adicionei a verificação para o caso em que esse valor era igual e coloquei como prova final.
